server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/activiti-demo?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 123456
  thymeleaf:
    cache: false
    enabled: true
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    content-type: text/html
    mode: LEGACYHTML5
    check-template-location: true
  # activiti default configuration
  activiti:
    database-schema-update: true
    check-process-definitions: false
    process-definition-location-prefix: classpath:processes/
    #    process-definition-location-suffixes:
    #      - **.bpmn
    #      - **.bpmn20.xml
    history-level: full

mybatis:
  type-aliases-package: cn.zephyr.module.entity
  mapper-locations:classpath*: cn/zephyr//dao/mapper/*.xml


logging:
  level:
    cn:
      zephyr:
        module:
          entity: debug

